---
title: C6312 | Microsoft Docs
ms.custom: ''
ms.date: 11/15/2016
ms.prod: visual-studio-dev14
ms.reviewer: ''
ms.suite: ''
ms.technology:
- vs-devops-test
ms.tgt_pltfrm: ''
ms.topic: article
f1_keywords:
- C6312
helpviewer_keywords:
- C6312
ms.assetid: 1fc8b9a1-e6ba-4799-84c3-31f289576cca
caps.latest.revision: 15
author: mikeblome
ms.author: mblome
manager: ghogen
ms.openlocfilehash: c2d627c4b8387e43b154ca6f2fb1d3ae334a70bd
ms.sourcegitcommit: af428c7ccd007e668ec0dd8697c88fc5d8bca1e2
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 11/16/2018
ms.locfileid: "51816767"
---
# <a name="c6312"></a>C6312
[!INCLUDE[vs2017banner](../includes/vs2017banner.md)]

Advertencia C6312: posible bucle infinito: uso de la constante EXCEPTION_CONTINUE_EXECUTION en la expresión de filtro de excepciones de try-excepto  
  
 Esta advertencia indica que el uso de la constante `EXCEPTION_CONTINUE_EXECUTION` (u otra constante que se evalúa como -1) en la expresión de filtro de controlador de excepciones estructurado. Uso del valor constante `EXCEPTION_CONTINUE_EXECUTION` podría dar lugar a un bucle infinito. Por ejemplo, si se generó una excepción por hardware, se reiniciará la instrucción que produjo la excepción. Si la dirección que produjo la excepción sigue siendo incorrecta, otro tipo de excepción se producirá y administrarse de la misma manera. Esto hace que un bucle infinito.  
  
 Una llamada explícita a `RaiseException` directamente no le causa un bucle infinito, pero continuará la ejecución del código en el bloque protegido. Esto puede ser inesperado y podría provocar un bucle infinito si `RaiseException` se usó para evitar la desreferenciación de un puntero no válido.  
  
 Por lo general, `EXCEPTION_CONTINUE_EXECUTION` debe devolver una función llamada en la expresión de filtro, que tiene la oportunidad de corregir, ya sea el puntero que produjo la excepción o la memoria subyacente.  
  
## <a name="example"></a>Ejemplo  
 El código siguiente genera esta advertencia:  
  
```  
#include <excpt.h>  
#include <stdio.h>  
#include <windows.h>  
  
void f (char *ptr)  
{  
  __try   
  {  
    // exception occurs if the caller passes null ptr  
    // code...     
   *ptr = '\0';  
  }   
  __except (EXCEPTION_CONTINUE_EXECUTION)  
    // When EXCEPTION_CONTINUE_EXECUTION is used, the handler  
    //  block of the structured exception handler is not executed.   
  {  
    puts("This block is never executed");  
  }  
}  
```  
  
 Para corregir esta advertencia, utilice el código siguiente:  
  
```  
#include <excpt.h>  
#include <stdio.h>  
#include <windows.h>  
  
void f (char *ptr)  
{  
  __try   
  {  
    // exception occurs if the caller passes null ptr  
    // code...  
    *ptr = '\0';  
  }   
  __except (GetExceptionCode()== EXCEPTION_ACCESS_VIOLATION ?   
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)   
  {  
    puts("Error Occurred");  
  }  
}  
```



