---
title: C6320 | Microsoft Docs
ms.custom: ''
ms.date: 11/15/2016
ms.prod: visual-studio-dev14
ms.reviewer: ''
ms.suite: ''
ms.technology:
- vs-devops-test
ms.tgt_pltfrm: ''
ms.topic: article
f1_keywords:
- C6320
helpviewer_keywords:
- C6320
ms.assetid: fb9e568e-b3d4-4ce2-a276-a64ad74d7b1e
caps.latest.revision: 12
author: mikeblome
ms.author: mblome
manager: ghogen
ms.openlocfilehash: cffb779f2b92cfee495480e2a1ba4946c5def605
ms.sourcegitcommit: af428c7ccd007e668ec0dd8697c88fc5d8bca1e2
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 11/16/2018
ms.locfileid: "51798123"
---
# <a name="c6320"></a>C6320
[!INCLUDE[vs2017banner](../includes/vs2017banner.md)]

Advertencia C6320: la expresión de filtro de excepciones es la constante EXCEPTION_EXECUTE_HANDLER. Esto puede enmascarar excepciones que no se esperaba que se controlaran  
  
 Esta advertencia indica que el efecto de usar la constante EXCEPTION_EXECUTE_HANDLER en el bloque __except. En este caso, la instrucción en el \_siempre se ejecutará el bloque _except para controlar la excepción, incluidas las excepciones que no deseaba administrar en una función determinada. Se recomienda que compruebe la excepción antes de controlarla.  
  
## <a name="example"></a>Ejemplo  
 El código siguiente genera esta advertencia porque el bloque __except intenta controlar las excepciones de todos los tipos:  
  
```  
#include <stdio.h>   
#include <excpt.h>   
  
void f(int *p)   
{   
   __try  
   {   
      puts("in try");   
      *p = 13;  // might cause access violation exception  
      // code ...  
   }   
   __except(EXCEPTION_EXECUTE_HANDLER) // warning  
   {   
      puts("in except");   
      // code ...  
   }   
}   
```  
  
 Para corregir esta advertencia, utilice `GetExceptionCode` para comprobar si una excepción determinada antes de controlarla, como se muestra en el código siguiente:  
  
```  
#include <stdio.h>   
#include <windows.h>   
#include <excpt.h>   
  
void f(int *p)   
{   
   __try  
   {   
      puts("in try");   
      *p = 13;    // might cause access violation exception   
      // code ...  
   }   
   __except(GetExceptionCode()==EXCEPTION_ACCESS_VIOLATION ?   
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)  
   {   
      puts("in except");   
      // code ...  
   }   
}  
```  
  
## <a name="see-also"></a>Vea también  
 [try-except (Instrucción)](http://msdn.microsoft.com/library/30d60071-ea49-4bfb-a8e6-7a420de66381)



