---
title: C6312
ms.date: 11/04/2016
ms.prod: visual-studio-dev15
ms.technology: vs-ide-code-analysis
ms.topic: reference
f1_keywords:
- C6312
helpviewer_keywords:
- C6312
ms.assetid: 1fc8b9a1-e6ba-4799-84c3-31f289576cca
author: mikeblome
ms.author: mblome
manager: wpickett
ms.workload:
- multiple
ms.openlocfilehash: 74ea9c013996ba29a3e29b724c41c3cac1e12127
ms.sourcegitcommit: e13e61ddea6032a8282abe16131d9e136a927984
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 04/26/2018
ms.locfileid: "31897064"
---
# <a name="c6312"></a>C6312
Advertencia C6312: posible bucle infinito: uso de la constante EXCEPTION_CONTINUE_EXECUTION en la expresión de filtro de excepción de un bloque try-excepto

 Esta advertencia indica el uso de la constante `EXCEPTION_CONTINUE_EXECUTION` (u otra constante que se evalúa como -1) en la expresión de filtro de un controlador de excepciones estructurado. Uso del valor constante `EXCEPTION_CONTINUE_EXECUTION` podrían dar lugar a un bucle infinito. Por ejemplo, si se produce una excepción con el hardware, se reiniciará la instrucción que produjo la excepción. Si la dirección que produjo la excepción sigue siendo incorrecta, otro tipo de excepción se producirá y administrarse de la misma manera. Esto hace que un bucle infinito.

 Una llamada explícita a `RaiseException` le directamente no causa un bucle infinito, pero continuará la ejecución del código en el bloque protegido. Esto puede ser inesperado y podría provocar un bucle infinito si `RaiseException` se usó para evitar la desreferenciación de un puntero no válido.

 Por lo general, `EXCEPTION_CONTINUE_EXECUTION` debe devolver una función denominada en la expresión de filtro, que tiene una oportunidad para corregir o el puntero que produjo la excepción o la memoria subyacente.

## <a name="example"></a>Ejemplo
 El código siguiente genera esta advertencia:

```
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *ptr)
{
  __try
  {
    // exception occurs if the caller passes null ptr
    // code...
   *ptr = '\0';
  }
  __except (EXCEPTION_CONTINUE_EXECUTION)
    // When EXCEPTION_CONTINUE_EXECUTION is used, the handler
    //  block of the structured exception handler is not executed.
  {
    puts("This block is never executed");
  }
}
```

 Para corregir esta advertencia, utilice el código siguiente:

```
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *ptr)
{
  __try
  {
    // exception occurs if the caller passes null ptr
    // code...
    *ptr = '\0';
  }
  __except (GetExceptionCode()== EXCEPTION_ACCESS_VIOLATION ?
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)
  {
    puts("Error Occurred");
  }
}
```